import type { Theme } from './types';

export const modernThemes: Theme[] = [
  {
    id: 'sspai',
    name: '少数派',
    description: '中文数字媒体标杆，经典红色标识与精致排版',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #d71a1b !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.01em;',
      h2: 'font-size: 22px; font-weight: 700; color: #333333 !important; line-height: 1.35 !important; margin: 32px 0 14px; padding-left: 12px; border-left: 4px solid #d71a1b;',
      h3: 'font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 12px;',
      h4: 'font-size: 16px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 20px 0 !important; line-height: 1.8 !important; color: #333333 !important;',
      strong: 'font-weight: 700; color: #d71a1b !important;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #d71a1b !important; text-decoration: none; border-bottom: 1px solid rgba(215,26,27,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.8 !important; color: #333333 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #fef7f7 !important; border-left: 4px solid #d71a1b; color: #555 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #fff5f5 !important; color: #d71a1b !important; border-radius: 4px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #fafafa !important; border-radius: 8px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #f0f0f0;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eee !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #fef7f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333 !important; border: 1px solid #f0e0e0;',
      td: 'padding: 12px 16px; border: 1px solid #f0e0e0; color: #333333 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'wechat',
    name: '微信原生',
    description: '原汁原味的官方绿底纹，满足传统阅读习惯',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ',
      h2: 'font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #333333 !important;',
      strong: 'font-weight: 700; color: #07c160 !important; background-color: rgba(7,193,96,0.08); padding: 0 4px; border-radius: 4px;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #07c160 !important; text-decoration: none; border-bottom: 1px solid #07c160; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #333333 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #f0f7f2 !important; border-left: 4px solid #07c160; color: #555 !important; border-radius: 4px; ',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0f7f2 !important; color: #07c160 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f0f7f2 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0f7f2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333333 !important; border: 1px solid #d8e8dc;',
      td: 'padding: 12px 16px; border: 1px solid #d8e8dc; color: #333333 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'apple',
    name: 'Mac',
    description: '纯净现代的极致留白，适合日常记录',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #1d1d1f !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ',
      h2: 'font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #1d1d1f !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #1d1d1f !important;',
      strong: 'font-weight: 700; color: #000 !important; ',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #1d1d1f !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #f5f5f7 !important; border-left: 4px solid #0066cc; color: #555 !important; border-radius: 4px; ',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f5f5f7 !important; color: #0066cc !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f5f5f7 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5f5f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #1d1d1f !important; border: 1px solid #e0e0e0;',
      td: 'padding: 12px 16px; border: 1px solid #e0e0e0; color: #1d1d1f !important;',
      tr: 'border: none;',
    }
  },
];
