import type { Theme } from './types';

export const modernThemes: Theme[] = [
  {
    id: 'sspai',
    name: '少数派',
    description: '中文数字媒体标杆，经典红色标识与精致排版',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #d71a1b !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.01em;',
      h2: 'font-size: 22px; font-weight: 700; color: #333333 !important; line-height: 1.35 !important; margin: 32px 0 14px; padding-left: 12px; border-left: 4px solid #d71a1b;',
      h3: 'font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 12px;',
      h4: 'font-size: 16px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 20px 0 !important; line-height: 1.8 !important; color: #333333 !important;',
      strong: 'font-weight: 700; color: #d71a1b !important;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #d71a1b !important; text-decoration: none; border-bottom: 1px solid rgba(215,26,27,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.8 !important; color: #333333 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #fef7f7 !important; border-left: 4px solid #d71a1b; color: #555 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #fff5f5 !important; color: #d71a1b !important; border-radius: 4px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #fafafa !important; border-radius: 8px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #f0f0f0;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eee !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #fef7f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333 !important; border: 1px solid #f0e0e0;',
      td: 'padding: 12px 16px; border: 1px solid #f0e0e0; color: #333333 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'notion',
    name: 'Notion',
    description: '极致克制的黑白灰，纯粹信息密度与无干扰写作',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #37352f !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 34px; font-weight: 700; color: #37352f !important; line-height: 1.2 !important; margin: 38px 0 8px; letter-spacing: -0.02em;',
      h2: 'font-size: 26px; font-weight: 600; color: #37352f !important; line-height: 1.3 !important; margin: 32px 0 8px;',
      h3: 'font-size: 21px; font-weight: 600; color: #37352f !important; line-height: 1.35 !important; margin: 28px 0 8px;',
      h4: 'font-size: 18px; font-weight: 600; color: #37352f !important; line-height: 1.4 !important; margin: 24px 0 8px;',
      p: 'margin: 4px 0 !important; line-height: 1.6 !important; color: #37352f !important;',
      strong: 'font-weight: 700; color: #37352f !important;',
      em: 'font-style: italic; color: #37352f !important;',
      a: 'color: #37352f !important; text-decoration: underline; text-underline-offset: 3px; text-decoration-color: rgba(55,53,47,0.4);',
      ul: 'margin: 4px 0; padding-left: 26px;',
      ol: 'margin: 4px 0; padding-left: 26px;',
      li: 'margin: 2px 0; line-height: 1.6 !important; color: #37352f !important;',
      blockquote: 'margin: 8px 0; padding: 4px 16px; background-color: transparent !important; border-left: 3px solid #37352f; color: #37352f !important; border-radius: 0;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 2px 5px; background-color: #f7f6f3 !important; color: #eb5757 !important; border-radius: 3px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 16px 0; padding: 20px; background-color: #f7f6f3 !important; border-radius: 4px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;',
      hr: 'margin: 24px auto; border: none; height: 1px; background-color: #e9e9e7 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 2px;',
      table: 'width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f7f6f3 !important; padding: 8px 12px; text-align: left; font-weight: 600; color: #37352f !important; border: 1px solid #e9e9e7;',
      td: 'padding: 8px 12px; border: 1px solid #e9e9e7; color: #37352f !important;',
      tr: 'border: none;',
    }
  },
];
